(import lsp.types types)
(defun expand-sym-string (symbol-to-expand &envir envir)
   (set current-pos (position symbol-to-expand))
   (set symbol-parts (map _(symbol (symbol _) (++ current-pos (+ (len _) 1))) (split (str symbol-to-expand) ":")))
   (if (eq (len symbol-parts) 1)
     (return symbol-to-expand)
   )
   (set symbol-symbols (list))
   (doit i (range 1 (len symbol-parts))
         (append symbol-symbols `(,\quote ,(index symbol-parts i)))
   )
   (set current-envir envir)
   (set current-sym null)
   (catch-all  
       (doit sym symbol-parts
          (if (in sym current-envir)
            (set current-envir (. current-envir sym))
            (set current-sym sym)
           else
            (set current-sym null)
            (break)
          )
       )
   )
   (if (not (eq current-sym null))
        (set res (signal ((index types 'semantic-token) current-sym  ((index types 'type-to-string) (type current-envir) ) )))
        (if (eq res "ligma") (print "yippieee"))
   )
  `(,\. ,@(index symbol-parts 0) ,@symbol-symbols)
)
(add-character-expander *READTABLE* ":" expand-sym-string)
