(import lsp.types types)
(defun expand-sym-string (symbol-to-expand)
   (setl current-pos (position symbol-to-expand))
   (setl symbol-parts (map _(symbol (symbol _) (++ current-pos (plus (len _) 1))) (split (str symbol-to-expand) ":")))
   (if (eq (len symbol-parts) 1)
     (return symbol-to-expand)
   )
   (setl symbol-symbols (list))
   (doit i (range 1 (len symbol-parts))
         (append symbol-symbols `(,\quote ,(symbol (index symbol-parts i) -1)))
   )
   (setl current-envir ((index types 'get-current-scope)))
   (setl current-sym null)
   (catch-all  
       (doit sym symbol-parts
          (if (in sym current-envir)
            (setl current-envir (. current-envir sym))
            (setl current-sym sym)
           else
            (setl current-sym null)
            (break)
          )
       )
   )
   (if (not (eq current-sym null))
        (setl res (signal ((index types 'semantic-token) current-sym  ((index types 'type-to-string) (type current-envir) ) )))
    else 
        (signal ((index types 'extra-diagnostic) (back symbol-parts)  "symbol not found"))
   )
  `(,\. ,@(index symbol-parts 0) ,@symbol-symbols)
)
(add-character-expander *READTABLE* ":" expand-sym-string)

